### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous

### ISSUE THREAD

**Issue by arycloud** [kriventsov/Clarke-and-Parkes-Error-Grids#1]
I'm trying to apply your `parkes_error_zone_detailed` function to the list of actual and predicted values for blood glucose but it's giving me an error as:

>  if above_line(0, 150, 35, 155) and above_line(35, 155, 50, 550):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Here's the code:
```
 def parkes_error_zone_detailed(act, pred, diabetes_type):
    def above_line(x_1, y_1, x_2, y_2, strict=False):
        if x_1 == x_2:
            return False

        act_0 = np.asanyarray(act)
        y_0 = y_1 - y_2
        first_exp = y_0*act_0
        print(first_exp)
        sec_exp = y_2 * x_1 - y_1 * x_2
        third_exp = x_1 - x_2
        y_line = (first_exp + sec_exp) / third_exp
        return pred > y_line if strict else pred >= y_line
```
it's for the type 1 diabetes and I'm passing the lists with float values for actual and predicted, what can be wrong here? it's pointing the `above_line` function for this error.

**Comment by kriventsov** [comment]
Hi, yes, thanks for letting me know, the lines that vectorized these functions for arrays were missing, I added them now. Please let me know if you still have issues.

**Comment by arycloud** [comment]
@kriventsov  How to grab the %age in different regions of the `Parkes error grid`?

**Comment by kriventsov** [comment]
100.0 * zone_accuracy(act_arr, pred_arr, mode='parkes')
Multiplying by 100 gives you percentages.

The result will be a numpy array such as, for example, [73.10, 21.90, 3.00, 1.50, 0.50], where 73.10% of all points would be in zone A, 21.90% in zone B, etc

If you want to differentiate between upper and lower regions with the same letter, then use 100.0 * zone_accuracy(act_arr, pred_arr, mode='parkes', detailed=True). This will give you a numpy array of 8 elements, corresponding to (A, lower B, upper B, lower C, upper C, lower D, upper D, E).

**Comment by arycloud** [comment]
@kriventsov  it's working correctly now, thank you!
